version: '3.8'

services:
  db:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - 13306:3306
    volumes:
      - ./defs/sql/ddl:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql

  pubsub:
    image: google/cloud-sdk:latest
    command: gcloud beta emulators pubsub start --project=local --host-port=0.0.0.0:8085
    ports:
      - 8085:8085

  datastore:
    image: google/cloud-sdk:latest
    command: gcloud beta emulators datastore start --project=local  --host-port=0.0.0.0:8081
    ports:
      - 8081:8081
    environment:
      DATASTORE_PROJECT_ID: local

  redis:
    image: redis:5.0
    ports:
      - 6379:6379

  web_client:
    build:
      context: .
      dockerfile: web_client.Dockerfile
    volumes:
    - ./src/web_client:/usr/src/app
    ports:
    - 3000:3000
    environment:
      NEXT_PUBLIC_AUTH_API_URL: http://localhost:4000

  account_service:
    build:
      context: .
      dockerfile: account_service.dev.Dockerfile
    volumes:
      - ./src/account_service:/go/src/app
    ports:
      - 4000:4000
      - 4040:4040
    env_file:
      - .env.public
      - .env
    environment:
      DB_URL: db:3306
      REDIS_URL: redis:6379
      PUBSUB_EMULATOR_HOST: pubsub:8085
    depends_on:
      - db
      - redis

  eitan_service:
    build:
      context: .
      dockerfile: eitan_service.dev.Dockerfile
    volumes:
      - ./src/eitan_service:/go/src/app
    ports:
      - 5000:5000
    env_file:
      - .env.public
      - .env
    environment:
      DB_URL: db:3306
      ACCOUNT_SERVICE_GRPC_URL: account_service:4040
      REDIS_URL: redis:6379
    depends_on:
      - account_service

  notificatoin_servie:
    build:
      context: .
      dockerfile: notification_service.dev.Dockerfile
    volumes:
      - ./src/notification_service:/go/src/app
    env_file:
      - .env.public
      - .env
    environment:
      PUBSUB_EMULATOR_HOST: pubsub:8085
      DATASTORE_EMULATOR_HOST: datastore:8081
    depends_on:
      - datastore
      - account_service

volumes:
  db_data:
