apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service-sa
  namespace: notification-service
  annotations:
    iam.gke.io/gcp-service-account: "notification-service-prod@eitan-prod.iam.gserviceaccount.com"
