// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Node interface {
	IsNode()
}

type UserProfile struct {
	ID           string  `json:"id"`
	Email        string  `json:"email"`
	DisplayName  string  `json:"displayName"`
	ScreenImgURL *string `json:"screenImgUrl"`
}

func (UserProfile) IsNode() {}

type UserProfilePublic struct {
	ID           string  `json:"id"`
	DisplayName  string  `json:"displayName"`
	ScreenImgURL *string `json:"screenImgUrl"`
}

func (UserProfilePublic) IsNode() {}

type ErrorCode string

const (
	ErrorCodeUnauthenticated ErrorCode = "UNAUTHENTICATED"
	ErrorCodeUnauthorized    ErrorCode = "UNAUTHORIZED"
	ErrorCodeAlreadyExist    ErrorCode = "ALREADY_EXIST"
	ErrorCodeInvalidArgument ErrorCode = "INVALID_ARGUMENT"
	ErrorCodeNotFound        ErrorCode = "NOT_FOUND"
	ErrorCodeInternal        ErrorCode = "INTERNAL"
)

var AllErrorCode = []ErrorCode{
	ErrorCodeUnauthenticated,
	ErrorCodeUnauthorized,
	ErrorCodeAlreadyExist,
	ErrorCodeInvalidArgument,
	ErrorCodeNotFound,
	ErrorCodeInternal,
}

func (e ErrorCode) IsValid() bool {
	switch e {
	case ErrorCodeUnauthenticated, ErrorCodeUnauthorized, ErrorCodeAlreadyExist, ErrorCodeInvalidArgument, ErrorCodeNotFound, ErrorCodeInternal:
		return true
	}
	return false
}

func (e ErrorCode) String() string {
	return string(e)
}

func (e *ErrorCode) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ErrorCode", str)
	}
	return nil
}

func (e ErrorCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Role string

const (
	RoleUser Role = "USER"
)

var AllRole = []Role{
	RoleUser,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleUser:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
