apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: api-eitan-com-issuer
  namespace: istio-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kanji.yy@gmail.com
    privateKeySecretRef:
      name: api-eitan-com-issuer
    solvers:
      - dns01:
          cloudDNS:
            project: eitan-prod
