apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  secretName: istio-ingressgateway-certs
  issuerRef:
    name: api-eitan-com-issuer
    kind: Issuer
  dnsNames:
    - api.eitan-flash.com
