apiVersion: v1
kind: ServiceAccount
metadata:
  name: account-service-sa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: "account-service-prod@335900057025.iam.gserviceaccount.com"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
      annotations:
        iam.gke.io/gcp-service-account: "account-service-prod@335900057025.iam.gserviceaccount.com"
    spec:
      serviceAccountName: account-service-sa
      containers:
        - name: server
          image: asia.gcr.io/eitan-prod/account_service:d9befa4b23c3596374c1d244d77924f1d110f6cb
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/healthz"
              port: 8080
          env:
            - name: PORT
              value: "8080"
            - name: APP_ENV
              value: "prod"
            - name: GCP_PROJECT_ID
              value: "eitan-prod"
            - name: ALLOWED_ORIGINS
              value: "https://eitan-flash.com"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  type: ClusterIP
  selector:
    app: account-service
  ports:
    - name: http
      port: 80
      targetPort: 8080