apiVersion: apps/v1
kind: Deployment
metadata:
  name: eitan-service
  namespace: eitan-service
spec:
  selector:
    matchLabels:
      app: eitan-service
  template:
    metadata:
      labels:
        app: eitan-service
    spec:
      serviceAccountName: eitan-service-sa
      containers:
        - name: server
          image: asia.gcr.io/eitan-prod/eitan-service:v0.0.1
          ports:
            - containerPort: 8000
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/healthz"
              port: 8000
          env:
            - name: PORT
              value: "8000"
            - name: APP_ENV
              value: "prod"
            - name: APP_ROOT_URL
              value: "https://api.eitan-flash.com"
            - name: GCP_PROJECT_ID
              value: "eitan-prod"
            - name: ALLOWED_ORIGINS
              value: "https://eitan-flash.com"

            - name: ACCOUNT_SERVICE_GRPC_URL
              value: "account-service.eitan-service.svc.cluster.local"

            - name: REDIS_URL
              value: "10.1.0.11:6379"
            - name: DB_NAME
              value: "eitandb"
            - name: DB_USER
              value: "eitan-service"
            # TODO: Don't hardcode and store in secure place
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eitan-service-secret
                  key: db_password
            - name: DB_URL
              value: "10.1.1.3:3306"

          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: eitan-service
  namespace: eitan-service
spec:
  type: ClusterIP
  selector:
    app: eitan-service
  ports:
    - name: http
      port: 80
      targetPort: 8000