
CREATE TABLE accountdb.users (
  id VARCHAR(255) NOT NULL PRIMARY KEY COMMENT 'ユーザーID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = 'ユーザー';

CREATE TABLE accountdb.user_profiles (
  user_id VARCHAR(255) NOT NULL PRIMARY KEY COMMENT 'ユーザーID',
  email VARCHAR (255) NOT NULL UNIQUE COMMENT 'Eメールアドレス',
  display_name VARCHAR(20) NOT NULL COMMENT 'ユーザー名',
  screen_img_url VARCHAR(255) COMMENT 'スクリーン画像',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY(user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  INDEX email_idx (email)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = 'ユーザー';

CREATE TABLE accountdb.google_auth (
  user_id VARCHAR(255) NOT NULL PRIMARY KEY COMMENT 'ユーザーID',
  google_id VARCHAR(255) NOT NULL UNIQUE COMMENT 'Google Account ID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY(user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = 'アカウント';
