CREATE TABLE eitandb.players (
  id VARCHAR(255) NOT NULL PRIMARY KEY COMMENT 'プレイヤーID',
  user_id VARCHAR(255) NOT NULL UNIQUE COMMENT 'ユーザーID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX user_id_idx (user_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = 'プレイヤープロフィール';

CREATE TABLE eitandb.match_waiting_players (
  player_id VARCHAR(255) NOT NULL PRIMARY KEY COMMENT 'ユーザーID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT match_waiting_players_ibfk_1 FOREIGN KEY(player_id) REFERENCES players(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '待機中プレイヤー';

CREATE TABLE eitandb.quiz_rooms (
  id VARCHAR(255) NOT NULL PRIMARY KEY COMMENT 'ルームID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = 'クイズルーム';

CREATE TABLE eitandb.quiz_room_players (
  quiz_room_id VARCHAR(255) NOT NULL COMMENT 'ルームID',
  player_id VARCHAR(255) NOT NULL COMMENT 'プレーヤーID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (quiz_room_id, player_id),
  CONSTRAINT quiz_room_players_ibfk_1 FOREIGN KEY(quiz_room_id) REFERENCES quiz_rooms(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT quiz_room_players_ibfk_2 FOREIGN KEY(player_id) REFERENCES players(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = 'クイズルーム入室中ユーザー';
