apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: account-service
spec:
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      serviceAccountName: account-service-sa
      containers:
        - name: server
          image: asia.gcr.io/eitan-prod/account-service:v0.0.1
          ports:
            - name: http
              containerPort: 8000
            - name: grpc
              containerPort: 8080
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 120
            failureThreshold: 3
          env:
            - name: REST_PORT
              value: "8000"
            - name: GRPC_PORT
              value: "8080"
            - name: APP_ENV
              value: "prod"
            - name: APP_ROOT_URL
              value: "https://api.eitan-flash.com"
            - name: WEB_APP_URL
              value: "https://eitan-flash.com"
            - name: GCP_PROJECT_ID
              value: "eitan-prod"
            - name: ALLOWED_ORIGINS
              value: "https://eitan-flash.com"
            - name: SESSION_COOKIE_DOMAIN
              value: "https://eitan-flash.com"
            - name: GOOGLE_AUTH_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  name: account-service-secret
                  key: google_auth_client_key
            # TODO: Don't hardcode and store in secure place
            - name: GOOGLE_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: account-service-secret
                  key: google_auth_secret
            - name: REDIS_URL
              value: "10.1.0.11:6379"
            - name: DB_NAME
              value: "accountdb"
            - name: DB_USER
              value: "account-service"
            # TODO: Don't hardcode and store in secure place
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: account-service-secret
                  key: db_password
            - name: DB_URL
              value: "10.1.2.5:3306"

          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: account-service
spec:
  type: ClusterIP
  selector:
    app: account-service
  ports:
    - name: http
      port: 80
      targetPort: 8000
