name: PubSub Publisher Job Workflow
on:
  push:
    paths:
      - ".github/workflows/pubsub_publisher_job.yml"
      - "src/pubsub_publisher_job/**"
      - "src/internal/**"
      - "src/pkg/**"

env:
  GO111MODULE: "on"
  TZ: "Asia/Tokyo"

jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go

      - name: Cache modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Download Modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: go mod download

      - name: Lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.33
          working-directory: src/pubsub_publisher_job

      - name: Test
        run: make test-pubsub-publisher-job

  push-image:
    name: Push Image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.PROD_GCP_CI_USER_KEY_BASE64 }}
          export_default_credentials: true

      - name: Push Docker Image to Prod GCR
        if: contains(github.ref, 'tags/v')
        run: |
          gcloud --quiet auth configure-docker
          docker build -t pubsub-publisher-job -f pubsub_publisher.Dockerfile .
          docker tag pubsub-publisher-job asia.gcr.io/eitan-prod/pubsub-publisher-job:${GITHUB_REF#refs/*/}
          docker push asia.gcr.io/eitan-prod/pubsub-publisher-job:${GITHUB_REF#refs/*/}
